
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slidemenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import new_project_ui
import project_ui
import crud
import re
import pandas as pd
class Ui_Project_Main(object):
    def openProjectsTab(self):
        self.stackedWidget.setCurrentIndex(1)
    def openDVTab(self):
        self.stackedWidget.setCurrentIndex(2)
    def openManualTab(self):
        self.stackedWidget.setCurrentIndex(3)
    def openAccountTab(self):
        self.stackedWidget.setCurrentIndex(4)
    def openLogOutTab(self):
        self.stackedWidget.setCurrentIndex(5)

        # show create project window
    def openNewProjectWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = new_project_ui.Ui_CreateNewProjectWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    # show the project task -- code for now --
    def openProjectTask(self):
        projectId = self.label_hidden.text()
        if projectId == "":
            print("User has not select any projects")
        else:
            self.window = QtWidgets.QMainWindow()
            self.ui = project_ui.Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()
            # showing existing project name, url, and inputs
            project_name = crud.read_project_name(self.label_hidden.text())
            URL = crud.read_project_url(self.label_hidden.text())
            user_inputs = crud.read_project_inputs(self.label_hidden.text())
            self.ui.lbl_pname.setText(project_name)
            self.ui.browser.setUrl(QtCore.QUrl(URL))
            self.ui.url_bar.setText(URL)
            # self.ui.txt_input1.setText(user_inputs[0])
            # self.ui.txt_input2.setText(user_inputs[1])

    # get the project ID from selected row
    def clicked_row(self):
        currentRow = self.projects_table.currentIndex().row()
        # only want first column -- project ID
        for j in range(1):
            if not self.projects_table.item(currentRow, j) is None:
                selected_project_id = self.projects_table.item(currentRow, j).text()
                # print(selected_project_id)
        self.label_hidden.setText(selected_project_id)
        print("label: ",self.label_hidden.text())
        # return selected_project_id

    def setupUi(self, Project_Main):
        Project_Main.setObjectName("Project_Main")
        Project_Main.resize(1106, 600)
        self.centralwidget = QtWidgets.QWidget(Project_Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QWidget(self.frame_2)
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.side_menu)
        self.frame_4.setMinimumSize(QtCore.QSize(200, 500))
        self.frame_4.setMaximumSize(QtCore.QSize(200, 700))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.project_button = QtWidgets.QPushButton(self.frame_4)
        self.project_button.setObjectName("project_button")
        self.verticalLayout_3.addWidget(self.project_button)
        self.dv_button = QtWidgets.QPushButton(self.frame_4)
        self.dv_button.setObjectName("dv_button")
        self.verticalLayout_3.addWidget(self.dv_button)
        self.manual_button = QtWidgets.QPushButton(self.frame_4)
        self.manual_button.setObjectName("manual_button")
        self.verticalLayout_3.addWidget(self.manual_button)
        self.account_button = QtWidgets.QPushButton(self.frame_4)
        self.account_button.setObjectName("account_button")
        self.verticalLayout_3.addWidget(self.account_button)


        self.label_hidden = QtWidgets.QLabel(self.frame_4)
        self.verticalLayout_3.addWidget(self.label_hidden)
        self.label_hidden.setHidden(True)

        self.userId_label = QtWidgets.QLabel(self.frame_4)
        self.verticalLayout_3.addWidget(self.userId_label)
        self.userId_label.setHidden(True)

        print("UserID: ", self.userId_label.text())

        self.logout_button = QtWidgets.QPushButton(self.frame_4)
        self.logout_button.setObjectName("logout_button")
        self.verticalLayout_3.addWidget(self.logout_button)

        self.project_button.clicked.connect(lambda: self.openProjectsTab())
        self.dv_button.clicked.connect(lambda: self.openDVTab())
        self.manual_button.clicked.connect(lambda: self.openManualTab())
        self.account_button.clicked.connect(lambda: self.openAccountTab())
        self.logout_button.clicked.connect(lambda: self.openLogOutTab())

        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.side_menu)
        self.main_body = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.label = QtWidgets.QLabel(self.MainPage)
        self.label.setGeometry(QtCore.QRect(230, 240, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.MainPage)
        self.Projects = QtWidgets.QWidget()
        self.Projects.setObjectName("Projects")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Projects)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.project_layout = QtWidgets.QVBoxLayout()
        self.project_layout.setContentsMargins(20, 20, 20, -1)
        self.project_layout.setObjectName("project_layout")
        self.newproject_button = QtWidgets.QPushButton(self.Projects)
        self.newproject_button.setMinimumSize(QtCore.QSize(120, 50))
        self.newproject_button.setMaximumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.newproject_button.setFont(font)
        self.newproject_button.setObjectName("newproject_button")
        self.project_layout.addWidget(self.newproject_button)
        self.newproject_button.clicked.connect(lambda: self.openNewProjectWindow())
        self.newproject_button.clicked.connect(lambda: Project_Main.close())

        self.open_project_button = QtWidgets.QPushButton(self.Projects)
        self.open_project_button.setMinimumSize(QtCore.QSize(120, 50))
        self.open_project_button.setMaximumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.open_project_button.setFont(font)
        self.open_project_button.setObjectName("open_project_button")
        self.project_layout.addWidget(self.open_project_button)

        self.projects_table = QtWidgets.QTableWidget(self.Projects)
        self.projects_table.setGridStyle(QtCore.Qt.SolidLine)
        self.projects_table.setObjectName("projects_table")
        self.project_layout.addWidget(self.projects_table)
        self.horizontalLayout_2.addLayout(self.project_layout)

        crud.read_specific_fields()

        # read csv file
        read_csv = pd.read_csv('project_details.csv')
        rows = len(read_csv)
        columns = len(read_csv.columns)
        header_labels = read_csv.columns

        # set the table widget
        self.projects_table.setRowCount(rows)
        self.projects_table.setColumnCount(columns)
        self.projects_table.setHorizontalHeaderLabels(header_labels)

        # put the data in table widget item
        for i in range(rows):
            for j in range(columns):
                self.projects_table.setItem(i, j, QtWidgets.QTableWidgetItem(str(read_csv.iat[i, j])))

        # resize the contents of the table
        self.projects_table.resizeColumnsToContents()
        self.projects_table.resizeRowsToContents()

        # for now -- user cannot edit the table
        self.projects_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        # open the project task window
        self.open_project_button.clicked.connect(lambda: self.openProjectTask())
        self.open_project_button.clicked.connect(lambda: Project_Main.close())
        # click the table widget to retrieve project ID
        self.projects_table.clicked.connect(lambda: self.clicked_row())

        self.stackedWidget.addWidget(self.Projects)
        self.DataVisualisation = QtWidgets.QWidget()
        self.DataVisualisation.setObjectName("DataVisualisation")
        self.label_2 = QtWidgets.QLabel(self.DataVisualisation)
        self.label_2.setGeometry(QtCore.QRect(190, 210, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.DataVisualisation)
        self.Manual = QtWidgets.QWidget()
        self.Manual.setObjectName("Manual")
        self.label_5 = QtWidgets.QLabel(self.Manual)
        self.label_5.setGeometry(QtCore.QRect(330, 210, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.Manual)
        self.Account = QtWidgets.QWidget()
        self.Account.setObjectName("Account")
        self.label_3 = QtWidgets.QLabel(self.Account)
        self.label_3.setGeometry(QtCore.QRect(180, 230, 231, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.Account)
        self.Logout = QtWidgets.QWidget()
        self.Logout.setObjectName("Logout")
        self.label_4 = QtWidgets.QLabel(self.Logout)
        self.label_4.setGeometry(QtCore.QRect(180, 240, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.Logout)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.main_body)
        self.verticalLayout.addWidget(self.frame_2)
        Project_Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Project_Main)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Project_Main)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Project_Main", "MainWindow"))
        self.project_button.setText(_translate("Project_Main", "Projects"))
        self.dv_button.setText(_translate("Project_Main", "Data Visualisation"))
        self.manual_button.setText(_translate("Project_Main", "Instruction Manual"))
        self.account_button.setText(_translate("Project_Main", "My Account"))
        self.logout_button.setText(_translate("Project_Main", "Log out"))
        self.label.setText(_translate("Project_Main", "Main Page"))
        self.newproject_button.setText(_translate("Project_Main", "New Project"))
        self.open_project_button.setText(_translate("Project_Main", "Open"))
        self.label_2.setText(_translate("Project_Main", "Data Visualisation "))
        self.label_5.setText(_translate("Project_Main", "Instruction Manual"))
        self.label_3.setText(_translate("Project_Main", "My Account"))
        self.label_4.setText(_translate("Project_Main", "Log Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Project_Main()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
